### ISSUE TITLE
TODO in DateCounter application :

### ISSUE THREAD

**Issue by marekbodziony** [marekbodziony/DateCounterAndroid#2]
TODO in DateCounter application :
- [x] save DateCounter in Database
- [ ] update DateCounter
- [x] delete DateCounter from saved list (and from Database)
- [ ] when "time left" will pass change type to "time pass"
